<a href="https://colab.research.google.com/github/sanjib-biswal-git/PYTHON-BASICS_AND_LIBRARIES/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY - INTRODUCTION

What is NumPy?
------------------

NumPy (Numerical Python) is a Python library used for:

Handling large, multi-dimensional arrays and matrices.

Performing mathematical operations (linear algebra, statistics, Fourier transforms, etc.) efficiently.

It is the foundation for Data Science, AI/ML, and scientific computing in Python.

Built on C and Fortran under the hood → that’s why NumPy is much faster than plain Python lists.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


# Numpy vs Python List


*Data types storage
*Importing module
*Numerical Operation
*Modification Capabilities
*consumes less memory
*fast as compare to python list.
*convenient to use.

List: [1,2,3,4,5] - comma separated
Array: [1 2 3 4 5]

In [ ]:
# %timeit
# nano - 10**-9
# micro - 10**-6

#list
%timeit [j**4 for j in range(1,9)]


782 ns ± 219 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:

#array
import numpy as np
%timeit np.arange(1,9)**4

2.01 µs ± 55.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
print(arr.ndim)

[1 2 3]
1


In [ ]:
#Taking the elements of the list as input then convert to numpy array.

l=[]
for i in range(1,5):
  inp=int(input("Enter element: "))
  l.append(inp)

print(np.array(l))

Enter element: 1
Enter element: 2
Enter element: 3
Enter element: 4
[1 2 3 4]


Dimensions in Arrays:

> 1-D Arrays []
> 2-D Arrays  [[]]
> 3-D Arrays  [[[]]]
> Higher Dimensional  Arrays


In [ ]:
# 1-D array
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [ ]:
# 2-D Array
arr =np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [ ]:
# 3-D Array
arr=np.array([[[1,2,3],[4,5,6]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


In [ ]:
#To create n-dimension array without using n sq. braces

# np.array([1,2,3],ndmin = n)

arr = np.array([1,2,3], ndmin=10)
print(arr)
print(type(arr))
print(arr.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
<class 'numpy.ndarray'>
10


#Creating NumPy arrays using NumPy function
#Spacial NumPy array
>Array filled with 0's
>Array filled with 1's
>Create an empty array
>An array with a range of elements
>Array diagonal elements filled with 1's
>Create an array with values that are spaced linearly in a specified interval.

In [ ]:
#Array filled with zeroes
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print("--------------")
print(ar_zero1)


[0. 0. 0. 0.]
--------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Array filled with ones
ar_one = np.ones(4)
ar_one1 = np.ones((3,4))
print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Create an empty array
ar_empty = np.empty(4);
print(ar_empty)   #[1. 1. 1. 1.] is output beacuse the previously stored array comes inside the empty array.

[1. 1. 1. 1.]


In [ ]:
#An array with a range of elements.
ar_range = np.arange(4);
ar_range2 = np.arange(5,31,5);  # [ 5 10 15 20 25 30] #st,en+1,step-length
print(ar_range)

[0 1 2 3]


In [ ]:
#Array diagonal element filled with 1's

ar_diag =np.eye(3) #3*3 2-D array will be created
ar_diag =np.eye(3,k=1) #upper triangular
ar_diag =np.eye(3,k=-1) #lower triangukar
print(ar_diag)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
# Create an array with values that are spaced linearly in a specified interval.

ar_lin = np.linspace(1,10,num=5) #st,en,no-of-element
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#Creating numpy array with random numbers.

rand() - random val b/w 0 and 1.

randn() - random val close to 0 , may return +ve or -ve numbers as well.

ranf() - fn for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0 , 1.0)

randint() -random number b/w a given range.

In [ ]:
#rand()

import numpy as np

var = np.random.rand(4)
var2 = np.random.rand(2,3)
print(var)
print("--------------")
print(var2)

[0.14585391 0.88007117 0.00805259 0.91833427]
--------------
[[0.51810686 0.34398772 0.6186955 ]
 [0.42589297 0.08087106 0.4304478 ]]


In [ ]:
#randn()

var = np.random.randn(5);
print(var)

[ 0.25678765  0.50900939  2.59359657 -2.81335764  1.08703406]


In [ ]:
#ranf()

var = np.random.ranf(4);
print(var)

[0.22325359 0.08319693 0.68352317 0.51925019]


In [ ]:
#randint()
var = np.random.randint(40,90,6);  # min,max,total_Values
print(var)

[86 44 84 69 61 53]


Data Type of Numpy Array
----------------------------

bool_ -  Boolean (True / False)
int_  - Default integer type
Intc - Identical to C int
Intp - Integer used for indexing
int8 - Byte(-128 to 127)
int16 - Integer (Gradually bigger ranges)
int32 - Integer
int64 - Integer
uint8 - Unsigned integer(0 to 255)
float_
complex_

In [ ]:
import numpy as np

var = np.array([1,2,3,4,5])
print("Data Type: ",var.dtype)

Data Type:  int64


In [ ]:

var = np.array([1.0,2,3,4,5])
print("Data Type: ",var.dtype)

Data Type:  float64


In [ ]:

var = np.array(["Sanjib","B","Y"])
print("Data Type: ",var.dtype)

Data Type:  <U6


In [ ]:

var = np.array([1,2,3,4,5,"A","B"])
print("Data Type: ",var.dtype)

Data Type:  <U21


#List of characters that are used to represent dtype in NumPy

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - Unicode string
V - the fixed chunk of memory for other types(void)

In [ ]:
#Change dtype

import numpy as np

var = np.array([1,2,3,4,5],dtype =np.int8)   #or can use the above short characters

# new = np.float32(var);  #another way
# new = var.astype(float); #another way

print("Data Type: ",var.dtype)   #int64 --> int8

Data Type:  int8


Numpy Arithmetic Operators
------------------------------
> a+b        np.add(a,b)
> a-b        np.subtract(a,b)
> a*b        np.multiply(a,b)
> a/b        np.divide(a,b)
> a%b        np.mod(a,b)
> a**b       np.power(a,b)
> 1/a        np.reciprocal(a)

In [ ]:
#Arithmetic operations on 1-D Array

import numpy as np

var = np.array([1,2,3,4])
var_add = var + 3;
print(var_add)

[4 5 6 7]


In [ ]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_add = var1+var2
#other ways
# var_add = np.add(var1,3);
# var_add = np.add(var1,var2);
print(var_add)

[2 4 6 8]


In [ ]:
#Arithmetic operations on 2-D Array

var2D_1 = np.array([[1,2,3,4],[1,2,3,4]])
var2D_2 = np.array([[1,2,3,4],[1,2,3,4]])

var_add_2D = var2D_1 + var2D_2;

print(var_add_2D)


[[2 4 6 8]
 [2 4 6 8]]


**Arithmetic Functions in Numpy**

> np.min(x)
> np.max(x)
> np.argmin(x)  #index of min value
> np.sqrt(x)
> np.sin(x)
> np.cos(x)
> np.cumsum(x)   #cumulative sum , running sum

In [ ]:
import numpy as np

var = np.array([1,2,3,4,5])

print(np.max(var))
print(np.min(var))
print(np.argmin(var))   #index of min value
print(np.argmax(var))   #index of max value
print(np.sqrt(var))
print(np.cumsum(var))  #running sum
print(np.sin(var))
print(np.cos(var))


5
1
0
4
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  3  6 10 15]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [ ]:
#2-D Array Stuff
# axis -0 (col k along)
# axis -1 (row k along)
var = np.array([[2,1,3],[9,5,6]])

print(np.min(var,axis=0))
print(np.min(var,axis=1))

[2 1 3]
[1 5]


**Shape and Reshaping in Numpy Arrays**



In [ ]:
c=np.array([[1,2],[1,2]])
print(c)
print()
print(c.shape)  #(row,col)

[[1 2]
 [1 2]]

(2, 2)


In [ ]:
var = np.array([1,2,3,4],ndmin=4)

print(var)
print(var.ndim)
print(var.shape)  #(r,r,r,c)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


In [ ]:
#Reshaping in numpy --> 1-D to MultiDimensional or vice-versa


#1-D ---> 2-D
var = np.array([1,2,3,4,5,6])
#reshape
x=var.reshape(3,2)  #(r,c)  #sufffient elems needed #no blank array in numpy
#3*2 = 6 no. of elements
print(x)



[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#1-D ---> 3-D

var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

x = var.reshape(2,2,3)

print(x)
print(x.ndim)

#from any dimension to one-dimension
one = x.reshape(-1)
print(one)
print(one.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


**BroadCasting in Numpy Arrays**



In [ ]:
#This is part of python not Numpy.
x=input() #'2'
y=input() #'3'
print(x+y)  #23

2
3
23


In [ ]:
x=int(input())
print(x) #'Hello"  ValueError: invalid literal for int() with base 10: 'Hello'

print(2**4//2**3)

3
3
2


In [ ]:
print("ABC")
print(2**4)

ABC
16


In [ ]:
if 2<=4<=5:
  print("LOL")

x=3
print(type(x))

LOL
<class 'int'>


In [ ]:
x=7
y=7
print(id(x))
print(id(y))  #id fn used to get the memory address

11642280
11642280


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.ndim)
print(arr.shape) #tuple ans #1-D array of size 5
print(arr.size)  #total no of elements

1
(5,)
5


# Indexing and Slicing

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[::2]) # step-slicing

10
50
[20 30 40]
[10 30 50]


# Shape Manipulation

In [ ]:
arr = np.arange(12)
print(arr)

reshaped = arr.reshape(3,4)
print("Reshaped:\n", reshaped)

flat = reshaped.flatten()
print("Flatten:", flat)

transposed = reshaped.T
print("Transpose:\n", transposed)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# Math Operations

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print("Mean:", arr.mean())
print("Std:", arr.std())
print("Sum:", arr.sum())


a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print("Dot:\n", np.dot(a,b))
print("Matrix mul:\n", np.matmul(a,b))


Mean: 3.5
Std: 1.707825127659933
Sum: 21
Dot:
 [[19 22]
 [43 50]]
Matrix mul:
 [[19 22]
 [43 50]]


# Random Module

In [ ]:
# Random numbers
print("rand:", np.random.rand(2,3))
print("randn:", np.random.randn(2,3))     # normal distribution
print("randint:", np.random.randint(1,10,(2,3))) # random ints
print("choice:", np.random.choice([10,20,30,40], size=5))


rand: [[0.43876251 0.72227174 0.63610552]
 [0.69416708 0.42637912 0.79936165]]
randn: [[ 1.44730303 -1.09181578 -0.65233336]
 [ 0.99177854 -0.83012688  0.23514915]]
randint: [[3 5 5]
 [4 6 2]]
choice: [20 20 20 20 40]
