<a href="https://colab.research.google.com/github/sanjib-biswal-git/PYTHON-BASICS_AND_LIBRARIES/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                 ** Numpy **


What is NumPy?
------------------

NumPy (Numerical Python) is a Python library used for:

Handling large, multi-dimensional arrays and matrices.

Performing mathematical operations (linear algebra, statistics, Fourier transforms, etc.) efficiently.

It is the foundation for Data Science, AI/ML, and scientific computing in Python.

Built on C and Fortran under the hood → that’s why NumPy is much faster than plain Python lists.

In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


Numpy vs Python List
--------------------------

*Data types storage
*Importing module
*Numerical Operation
*Modification Capabilities
*consumes less memory
*fast as compare to python list.
*convenient to use.

List: [1,2,3,4,5] - comma separated
Array: [1 2 3 4 5]

In [14]:
# %timeit
# nano - 10**-9
# micro - 10**-6

#list
%timeit [j**4 for j in range(1,9)]


782 ns ± 219 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:

#array
import numpy as np
%timeit np.arange(1,9)**4

2.01 µs ± 55.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
print(ndim(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [25]:
#Taking the elements of the list as input then convert to numpy array.

l=[]
for i in range(1,5):
  inp=int(input("Enter element: "))
  l.append(inp)

print(np.array(l))

Enter element: 1
Enter element: 2
Enter element: 3
Enter element: 4
[1 2 3 4]


Dimensions in Arrays:

> 1-D Arrays []
> 2-D Arrays  [[]]
> 3-D Arrays  [[[]]]
> Higher Dimensional  Arrays


In [26]:
# 1-D array
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [31]:
# 2-D Array
arr =np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [32]:
# 3-D Array
arr=np.array([[[1,2,3],[4,5,6]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


In [35]:
#To create n-dimension array without using n sq. braces

# np.array([1,2,3],ndmin = n)

arr = np.array([1,2,3], ndmin=10)
print(arr)
print(type(arr))
print(arr.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
<class 'numpy.ndarray'>
10
